adding timestamp features
nel-lab/mesmerize-core pull request #141
Opened 2022-12-10 15:28 UTC by clewis7

addresses #127 

human readable timestamp added when item added to dataframe and ran time stamp is added when item is ran

just trying to get back into the swing of things, thought this would be a good one to implement!!

2022-12-10 20:08 UTC, kushalkolar requested changes

2022-12-10 21:08 UTC, kushalkolar commented
linux test failing but windows test passing? I don't even :open_mouth:

2022-12-13 05:23 UTC, kushalkolar commented on mesmerize_core/algorithms/cnmf.py
> +    df.loc[df["uuid"] == uuid, "ran_time"] = datetime.now().isoformat(timespec="milliseconds")
does this return in the local timezone?

2022-12-13 05:23 UTC, kushalkolar commented on mesmerize_core/algorithms/cnmf.py
> +    df.loc[df["uuid"] == uuid, "ran_time"] = datetime.now().isoformat(timespec="milliseconds")
how much extra info is kept with this, we really only want YYYY-MM-DD-HH-MM-SS

2022-12-13 15:58 UTC, clewis7 commented on mesmerize_core/algorithms/cnmf.py
> +    df.loc[df["uuid"] == uuid, "ran_time"] = datetime.now().isoformat(timespec="milliseconds")
will fix to only return up to seconds

returns local time zone as established on the computer

2022-12-13 16:02 UTC, clewis7 commented on mesmerize_core/algorithms/cnmf.py
> +    df.loc[df["uuid"] == uuid, "ran_time"] = datetime.now().isoformat(timespec="milliseconds")
file:///home/caitlin/Desktop/timestamp_ex.png

2022-12-13 16:03 UTC, clewis7 commented on mesmerize_core/algorithms/cnmf.py
> +    df.loc[df["uuid"] == uuid, "ran_time"] = datetime.now().isoformat(timespec="milliseconds")
![timestamp_ex](https://user-images.githubusercontent.com/69729525/207383103-ca394e94-bd3e-465c-bf8f-1c791eaae1de.png)

2022-12-13 18:29 UTC, kushalkolar commented on mesmerize_core/algorithms/cnmf.py
> +    df.loc[df["uuid"] == uuid, "ran_time"] = datetime.now().isoformat(timespec="milliseconds")
is `/` the default separator for this? Is there a way to get a different separator? maybe `T`?

2022-12-20 16:22 UTC, clewis7 commented
I think everything should be fixed here, let me know if there is anything else :)

2022-12-21 03:55 UTC, kushalkolar approved these changes
LGTM, will merge if CI passes

2022-12-21 04:40 UTC, kushalkolar commented
CI is failing because new numpy deprecated `numpy.int` and caiman uses them :man_facepalming:

2023-01-07 07:14 UTC, merged

2023-01-07 07:14 UTC, kushalkolar commented
thanks! @clewis7