Do not export unnecessary conda env vars, use conda run
nel-lab/mesmerize-core pull request #232
Opened 2023-10-09 21:38 UTC by rly

Fix #230

2023-10-09 21:40 UTC, rly commented
Tests pass when run locally except for the error `TypeError: float() argument must be a string or a real number, not 'coo_matrix'` reported in #231.

2023-10-09 21:55 UTC, kushalkolar commented
I wonder if this coo_matrix is due to some recent change with caiman.

2023-10-09 21:56 UTC, kushalkolar commented
Because we didn't have it before.

2023-10-09 22:15 UTC, kushalkolar requested changes

2023-10-09 22:15 UTC, kushalkolar commented on mesmerize_core/utils.py
> +                f.write(f'conda run -p {os.environ["CONDA_PREFIX"]} python {module_path} {args_str}')
This would assume that conda is findable in the shell env that that is launched by the subprocess and I don't think that's going to be the case if the conda binary isn't in the PATH env variable.

2023-10-09 22:15 UTC, kushalkolar commented on mesmerize_core/utils.py
> +                f.write(f'conda run -p {os.environ["CONDA_PREFIX"]} python {module_path} {args_str}')
Is "conda run" the best way to do this? If so then the fully path to the conda executable should be used.

2023-10-09 22:15 UTC, kushalkolar commented on mesmerize_core/utils.py
> -                    f'export CONDA_PYTHON_EXE={os.environ["CONDA_PYTHON_EXE"]}\n'
Are we sure this is no longer necessary?

2023-10-09 22:36 UTC, kushalkolar commented on mesmerize_core/utils.py
> -                    f'export CONDA_PYTHON_EXE={os.environ["CONDA_PYTHON_EXE"]}\n'
I mean the `CONDA_PYTHON_EXE`

2023-11-10 17:21 UTC, rly commented on mesmerize_core/utils.py
> -                    f'export CONDA_PYTHON_EXE={os.environ["CONDA_PYTHON_EXE"]}\n'
I believe these env variables will not do anything if the conda environment is not activated and you call the default `python` below.

2023-11-10 18:36 UTC, rly commented
This works locally on my Mac M1 system.
Steps:
1. create conda environment
2. run through one of the notebooks like mcorr_cnmf.ipynb up to the `df.iloc[0].caiman.run()` step
3. the cell runs successfully
4. deactivate conda environment
5. call the runfile without any conda environment activated (not even base). the shell script runs successfully!

relevant env vars without any conda env activated are:
```
CONDA_CHANGEPS1=no
CONDA_EXE=/Users/rly/mambaforge/bin/conda
_CE_M=
_CE_CONDA=
CONDA_PYTHON_EXE=/Users/rly/mambaforge/bin/python
CONDA_SHLVL=0
```

2023-11-10 18:40 UTC, rly commented on mesmerize_core/utils.py
> +                f.write(f'conda run -p {os.environ["CONDA_PREFIX"]} python {module_path} {args_str}')
An alternative is to activate the conda environment and then run python, but `conda activate` within a shell script can be tricky.

2023-11-10 18:47 UTC, rly commented on mesmerize_core/utils.py
> +                f.write(f'conda run -p {os.environ["CONDA_PREFIX"]} python {module_path} {args_str}')
I would go with `conda run`

2024-05-17 22:38 UTC, ethanbb commented
This is working for me (on Linux).

2024-05-17 22:44 UTC, merged