Allow non-hashable types and nested params in get_params_diffs
nel-lab/mesmerize-core pull request #297
Opened 2024-05-20 02:40 UTC by ethanbb

This extends the function `get_params_diffs` to work when the params are nested under different groups (as caiman now expects) and/or include types that are comparable but not hashable, such as lists. (The hashability issue comes from creating a `set`, which requires elements to be hashable; after playing a bit with converting non-hashable types to hashable ones, I decided to bypass that entirely by just using a different method based on equality testing.)

I had to make these changes to get it to work with my existing code, where I am exporting the entire params dict from a CNMFParams object and modifying it as needed before passing to `df.caiman.add_item`. I figured it could help others to make this function more robust.

2024-05-20 03:44 UTC, kushalkolar requested changes
Thanks!, mostly LGTM, comments would be useful

2024-05-20 03:44 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +        def get_all_params(params_dict: dict):
add docstring

2024-05-20 03:44 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +            return tuple(params)
add comments

2024-05-20 03:44 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +        def get_specific_params(params_dict: dict, param_names: list[str]):
add docstring and comments

2024-05-20 03:44 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +        first_values = {}
add comment, does this hold?

2024-05-20 03:44 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +                if key not in first_values:
add comment

2024-05-20 03:44 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +                elif not np.isscalar(first_values[key]) or not np.isscalar(val):
add comment

2024-05-20 03:44 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +                elif first_values[key] != val:
add comment

2024-05-20 06:18 UTC, ethanbb commented on mesmerize_core/caiman_extensions/common.py
> +        first_values = {}
I guess one way it could fail is if some items set a parameter to a particular value, overriding the default, and others leave it out to use the default. E.g. this could happen if you initially didn't care about a parameter, but then tried changing it to something else. To account for this, I switched to maintaining a dict of parameters that have been seen so far and moving them to the set of varying parameters if they are ever present in one item and not another. Will be in the next push.

2024-05-31 19:48 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +                        params[f"{key1}.{key2}"] = val2
none of the params have a `.` ?

2024-05-31 19:55 UTC, kushalkolar commented
By the way, did the lockfile stuff in your other branch work?

2024-06-03 02:04 UTC, ethanbb commented on mesmerize_core/caiman_extensions/common.py
> +                        params[f"{key1}.{key2}"] = val2
I don't believe so, because they all have to be valid keyword parameter names for the CNMFParams __init__ function (at least until the deprecated way of initializing CNMFParams is removed, but refactoring at that point to add dots in parameter names would just be asking for things to break...)

2024-06-03 02:06 UTC, ethanbb commented
> By the way, did the lockfile stuff in your other branch work?

Probably, still doing some testing though.

2024-06-05 23:38 UTC, kushalkolar commented
is this good to go to merge?

2024-06-05 23:53 UTC, ethanbb commented
> is this good to go to merge?

Yes it should be!

2024-06-06 00:05 UTC, merged