Run items using SLURM
nel-lab/mesmerize-core pull request #298
Opened 2024-06-07 14:41 UTC by ethanbb

This implements the "slurm" backend via `_run_slurm`. Supports passing a partition or list of partitions on which to run the jobs; more options (such as memory allocation) could be added if we think they're important.

For controlling number of CPUs/processes per job, right now I'm using the MESMERIZE_N_PROCESSES environment variable to indicate how many processes to use *per job*, which matches the behavior of the "subprocess" backend. However, it might be a good idea to instead divide this number by the number of jobs that are running in parallel, to avoid needlessly over-parallelizing each job. I'm doing this in my own code to set the environment variable and it works fine, but it may make sense to automate it.

2024-06-07 16:15 UTC, ethanbb commented
Changed to draft because I'm actually still refactoring things as part of the cross-platform saving fix

2024-06-11 16:27 UTC, ethanbb commented
tox-dev/filelock#331 is currently a blocker... could probably sidestep but I'm hoping they fix it quickly (for now)

2024-06-13 22:48 UTC, ethanbb commented
This now also fixes #209 - sorry for the lack of clean separation between them. Locking the batch file while writing was involved in both sets of changes.

2024-06-15 07:36 UTC, kushalkolar requested changes
Thanks! Mostly LGTM, have a few suggestions

2024-06-15 07:36 UTC, kushalkolar commented on mesmerize_core/algorithms/cnmf.py
> +from pathlib import Path, PurePosixPath
`PurePosixPath` as opposed to `PosixPath` because I guess `PosixPath` would faile on windows?

2024-06-15 07:36 UTC, kushalkolar commented on mesmerize_core/batch_utils.py
> +    pass
```suggestion
class PreventOverwriteError(IndexError):
    """
    Error thrown when trying to write to an existing batch file with a potential risk of removing existing rows.
    """
    pass
```

2024-06-15 07:36 UTC, kushalkolar commented on mesmerize_core/batch_utils.py
> +        self.lock.__exit__(exc_type, exc_value, traceback)
I'm not familiar with the `lockfile` lib but is this how it's intended to be used? It's kinda confusing. This is a composition but seems like subclassing might be more suitable?

2024-06-15 07:36 UTC, kushalkolar commented on mesmerize_core/batch_utils.py
> +    return BatchLock(batch_path)
seems like this isn't required

2024-06-15 07:36 UTC, kushalkolar commented on mesmerize_core/batch_utils.py
> +def save_results_safely(batch_path: Union[Path, str], uuid, results: dict, runtime: float):
```suggestion
def save_algo_to_df(batch_path: Union[Path, str], uuid, results: dict, runtime: float):
```

2024-06-15 07:36 UTC, kushalkolar commented on mesmerize_core/batch_utils.py
> +    which gives up after lock_timeout seconds (set to -1 to never give up)
```suggestion
    which gives up after `lock_timeout` seconds.
```

probably not a good idea to ever set timeout to `-1`

2024-06-15 07:36 UTC, kushalkolar commented on mesmerize_core/batch_utils.py
> +        raise RuntimeError(msg)
This might make more sense to have as a dataframe extension :thinking: . We have `save_to_disk()`, this is basically `save_to_disk_with_lock()`

2024-06-15 07:36 UTC, kushalkolar commented on mesmerize_core/batch_utils.py
> +        # Print a message with details in lieu of writing to the batch file
might be a good idea to write to a file because messages can be _very long_ especially when sklearn is spitting out gigabytes of deprecation warnings :laughing: 

Maybe to `<uuid>.error` or something

2024-06-15 07:36 UTC, kushalkolar commented on mesmerize_core/batch_utils.py
> +    except BaseException as e:
```suggestion
except (Timeout, PreventOverwriteError) as e:
```

`BaseException` should never be used AFAIK

2024-06-15 07:36 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +        self.save_to_disk(max_index_diff=1)
good catch!

2024-06-15 07:36 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +        partition: Optional[Union[str, list[str]]] = None,
what about just allowing the user to pass an arbitrary string that's appended to the submission command? Gives them full flexibility to customize things

2024-06-15 07:36 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +            submission_opts += f' --partition={",".join(partition)}'
I think it's cleaner and more veratile to just allow passing an arbitrary string of slurm args to append

2024-06-15 07:36 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +        # --wait means that the lifetme of the created process corresponds to the lifetime of the job
what happens otherwise?

2024-06-15 16:36 UTC, ethanbb commented on mesmerize_core/algorithms/cnmf.py
> +from pathlib import Path, PurePosixPath
Correct - from the pathlib documentation:
>If you want to manipulate Windows paths on a Unix machine (or vice versa). You cannot instantiate a [WindowsPath](https://docs.python.org/3/library/pathlib.html#pathlib.WindowsPath) when running on Unix, but you can instantiate [PureWindowsPath](https://docs.python.org/3/library/pathlib.html#pathlib.PureWindowsPath).

2024-06-15 16:57 UTC, ethanbb commented on mesmerize_core/batch_utils.py
> +        self.lock.__exit__(exc_type, exc_value, traceback)
I tried subclassing it at first, but it wasn't working properly in some way (don't remember). I figured it would be simpler to use composition instead, but I could try subclassing again now that I understand it a little better. 

However, doing so would give us a little less flexibility as the subclass `__init__` method would have to be compatible with the [`__new__` method of `BaseFileLock`](https://github.com/tox-dev/filelock/blob/3d7b1a6276144bdbad0086067feb36e1c1a8d2f7/src/filelock/_api.py#L85) (assuming we don't want to overrride `__new__` as well, which I would really feel uncomfortable with). This does allow arbitrary keyword arguments to be passed, but that's not as clean as a single positional argument. Furthermore, we would have to somehow pass the name of the lockfile and the flag `is_singleton=True` to the superclass `__new__`, meaning I guess that the construction of our subclass would have to be hidden behind a factory function. At that point I don't see any advantage to subclassing.

If there is a way to make a context manager with the same behavior without writing a new class at all, that would be my preference.

2024-06-15 17:01 UTC, ethanbb commented on mesmerize_core/batch_utils.py
> +        # Print a message with details in lieu of writing to the batch file
What if we did this always and just stored the path to this file rather than the actual tracepack in `outputs`? or is that too breaking?

2024-06-15 17:04 UTC, ethanbb commented on mesmerize_core/caiman_extensions/common.py
> +        # --wait means that the lifetme of the created process corresponds to the lifetime of the job
Otherwise, `sbatch` submits the job and then exits. There may be another way to track the progress of the job after `sbatch` returns, but this seemed easiest.

2024-06-15 17:05 UTC, ethanbb commented on mesmerize_core/caiman_extensions/common.py
> +            submission_opts += f' --partition={",".join(partition)}'
Yes good point! Will change.

2024-06-15 17:44 UTC, ethanbb commented on mesmerize_core/batch_utils.py
> +    except BaseException as e:
Probably `Exception` is better than `BaseException` as we wouldn't want keyboard interrupts to be treated in the same way. But my intention was to make sure a runtime error doesn't get lost if there is a failure to write to the batch file for *any* reason.

This is less important if we do always log errors to some file within the item directory, so even if saving fails, that can be inspected.

2024-06-15 21:31 UTC, ethanbb commented on mesmerize_core/batch_utils.py
> +    return BatchLock(batch_path)
agree, I am redesigning all this

2024-06-15 21:32 UTC, ethanbb commented on mesmerize_core/batch_utils.py
> +        raise RuntimeError(msg)
Yes! will push update soon

2024-06-15 22:37 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +        # --wait means that the lifetme of the created process corresponds to the lifetime of the job
Ok, I'm just not familiar with slurm so I didn't understand what this is for :)

2024-06-15 22:39 UTC, kushalkolar commented on mesmerize_core/batch_utils.py
> +    except BaseException as e:
Ah I see, then yes use broad Exception instead of base

2024-06-16 00:39 UTC, ethanbb commented
I made some significant changes to put the saving functionality in the `caiman` dataframe extension and streamline locking the file where necessary - please take another look when you can!

2024-06-16 00:43 UTC, ethanbb commented
Hmm checks seem to be failing at the install step - not sure if it's due to these changes or something else is going on.

2024-06-19 04:47 UTC, kushalkolar requested changes

2024-06-19 04:47 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/_utils.py
> +def _verify_and_lock_batch_file(func):
this is a very nice way to do it!

2024-06-19 04:47 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +        Update the item with the given uuid with the data in updated_row and write to disk.
what's `updated_row`?

2024-06-19 04:47 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +        index: int, str or UUID
put type annotation in function signature too

2024-06-19 04:47 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +            should match a column name. If not, that data will not be saved.
> If not, that data will not be saved.

should probably throw an error then?

2024-06-19 04:47 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +    def update_item_with_results(self, uuid: Union[str, UUID], results: dict, run_duration: float):
can this be decorated?

2024-06-19 04:47 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +    def update_item_with_results(self, uuid: Union[str, UUID], results: dict, run_duration: float):
ah I guess we don't want to decorate this because we want to catch the exception and dump the error to disk

2024-06-19 04:47 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +    def _save_to_disk_unsafe(self):
docstring that this function should never be used directly

2024-06-19 04:47 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/common.py
> +    def save_to_disk(self):
checking `max_index_diff` is still very important. BTW since this is a stable package please point out any API changes in PRs :smile: 

Example of why this is important:

```python
df = <load big df from disk>

sub_df = df[df["item_name"] == "some item"]

sub_df.save_to_disk()  # this will overwrite the entire original dataframe with the smaller dataframe!
```

2024-06-19 04:48 UTC, kushalkolar commented
have a few comments, sorry been busy with a big `fastplotlib` release. You can always always ping me with @ if I forget

2024-06-19 14:11 UTC, ethanbb commented on mesmerize_core/caiman_extensions/common.py
> +            should match a column name. If not, that data will not be saved.
You're right, I was being lazy and hoped there was a way in pandas to update "strictly," but didn't find one so went with this. But I'll change it.

2024-06-19 14:17 UTC, ethanbb commented on mesmerize_core/caiman_extensions/common.py
> +        index: int, str or UUID
So I don't know what the best practice is with this, but isn't it correct given that the code of this function accepts only ints? On the other hand, because of decoration by `@_index_parser`, `CaimanDataFrameExtensions.update_item` accepts ints, strs, and UUIDs. However, I agree it is confusing; most people probably look to function signatures rather than docstrings to learn how to call things.

2024-06-19 14:18 UTC, ethanbb commented on mesmerize_core/caiman_extensions/common.py
> +        Update the item with the given uuid with the data in updated_row and write to disk.
Sorry, outdated docstring.

2024-06-19 14:19 UTC, ethanbb commented on mesmerize_core/caiman_extensions/_utils.py
> +def _verify_and_lock_batch_file(func):
Thanks :)

2024-06-19 15:04 UTC, ethanbb commented
No worries, I've been working on other things as well.

2024-06-19 15:10 UTC, ethanbb commented on mesmerize_core/caiman_extensions/common.py
> +    def save_to_disk(self):
Re the example - this will currently fail, because it will be caught by `@_verify_and_lock_batch_file`.

It's true this is an API change - I am still getting used to dealing with stable public APIs! I was thinking that with the new checking/locking before calling `add_item` and `remove_item`, we would never have to use a nonzero `max_index_diff`, but I guess external code could be doing something weird and relying on it.

Even if I added `max_index_diff` back in so the signature matches, the behavior in `@_verify_and_lock_batch_file` is now stricter; it checks whether the full list of UUIDs matches what is on disk, not just the number of rows. Do you think this would be breaking/is it worth using the less strict behavior for just this function? Also, should passing something in for `max_index_diff` be deprecated?

2024-06-19 15:45 UTC, ethanbb commented on mesmerize_core/caiman_extensions/common.py
> +        except BaseException as err:
Yes `BaseException`, however here I believe it's correct (at least matches previous behavior); just need to put it explicitly in order to get `err` so it can be forwarded.

2024-06-19 15:46 UTC, ethanbb commented
@kushalkolar done making changes for now; see remaining threads for questions I still have

2024-07-16 18:29 UTC, kushalkolar requested changes

2024-07-16 18:40 UTC, merged