Fix motion correction for 3D movies
nel-lab/mesmerize-core pull request #300
Opened 2024-06-14 20:20 UTC by ethanbb

The mcorr algorithm currently fails when run on a 3D movie during correlation image calculation. This is due to some code in caiman that could probably also be changed to get it to work (flatironinstitute/caiman#1363 does half of it), but this PR should fix mcorr in a way that is also compatible with existing caiman versions: 

- By passing the file in as a string rather than list, `load_file_chain` does not get called, which means `is3D` is not needed (otherwise this throws an error).
- I added a try/catch that should catch the specific bug fixed in flatironinstitute/caiman#1363 and tries again without baseline removal to avoid it.

This PR is dependent on #298 (to avoid an ugly merge) so I'm submitting it as a draft for now. Also, it would be good to add a test case for 3D motion correction (with test data and everything). But at least the current tests pass (except for the 2 that are always failing) so it doesn't break 2D mcorr.

2024-06-15 07:49 UTC, kushalkolar commented
rebase this on main once #298 is merged

2024-07-16 18:50 UTC, kushalkolar commented
wait until next release of caiman and then pin the next release of mescore to that

2024-07-24 19:58 UTC, ethanbb commented
Caiman PR is merged, but still waiting for next release to mark as ready for review.

2024-07-31 16:46 UTC, ethanbb commented
Caiman 1.11.2 is released

2024-08-11 06:30 UTC, kushalkolar requested changes
sorry for the response, few minor comments mostly because I haven't been keeping up with what's happening on caiman

2024-08-11 06:30 UTC, kushalkolar commented on mesmerize_core/algorithms/mcorr.py
> +            str(mcorr_memmap_path),
did this change in the latest release of caiman 
from a `list[str]` to just `str`?

2024-08-11 06:30 UTC, kushalkolar commented on mesmerize_core/algorithms/cnmf.py
> +        Cn = cm.local_correlations(images, swap_dim=False)
is this according to a recent change in the latest release of caiman?

2024-08-11 06:47 UTC, ethanbb commented on mesmerize_core/algorithms/mcorr.py
> +            str(mcorr_memmap_path),
So that function says it takes a `str`. You can pass it a list, but that just triggers `movies.load` to call `load_movie_chain` to concatenate the movies together. However, `load_movie_chain` requires `is3D` to be specified correctly, whereas just `load` with a string does not. So to simplify things, I got rid of the list.

2024-08-11 06:52 UTC, ethanbb commented on mesmerize_core/algorithms/cnmf.py
> +        Cn = cm.local_correlations(images, swap_dim=False)
It's not a recent change; it looks like this transpose was just to correct for the dim-swapping that is done by default, but instead we can just disable it by setting `swap_dim=False`. (I had to deal with this line b/c the arguments to `transpose` would be different for 3D movies.)

2024-08-22 14:10 UTC, kushalkolar commented
Lgtm!

2024-08-22 14:11 UTC, kushalkolar approved these changes

2024-08-22 14:30 UTC, merged