making caiman.run() common extension callbacks_finished arg optional
nel-lab/mesmerize-core pull request #45
Opened 2022-06-09 02:55 UTC by clewis7

addressing issue #23 

made ```callbacks_finished``` arg optional, should no longer cause problem of having to input arg for ```callbacks_finished``` as ```print[]``` when running function in jupyter lab!!

2022-06-09 03:04 UTC, kushalkolar commented
@clewis7 thanks! You'll also have to change the code around here to something like `if callbacks_finished is not none:` https://github.com/nel-lab/mesmerize-core/blob/070890f4080d3573440fbfde4d98ddacf7b9371a/mesmerize_core/caiman_extensions/common.py#L159

2022-06-09 20:03 UTC, kushalkolar requested changes

2022-06-09 20:03 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cnmf.py
> +        ixs_frames: Tuple[int, int], int
add to the docstring below that it can also just return a single frame

2022-06-09 20:03 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cnmf.py
> +        ixs_frames: Tuple[int, int], int
You will also need to add a check around line 245 that `if type(ixs_frames) is int`, create a tuple of ints to actually use for indexing which is then used for further indexing.

2022-06-09 20:07 UTC, kushalkolar approved these changes

2022-06-09 20:07 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cnmf.py
> +        ixs_frames: Optional[Tuple[int, int], int] = None,
also tests are failing because this is wrong typing syntax, I think this is the correct syntax if you have multiple optional types:

```python
Optional[Union[Tuple[int, int], int]]
```

2022-06-10 04:57 UTC, kushalkolar requested changes

2022-06-10 04:57 UTC, kushalkolar commented on tests/test_core.py
> +    # test to check passing optional ixs components to various functions
what's with all the tests stuff in this PR/branch?

2022-06-10 04:58 UTC, kushalkolar commented
goodluck on the linalg test, don't worry about the code review until then!

2022-06-10 13:18 UTC, clewis7 commented on tests/test_core.py
> +    # test to check passing optional ixs components to various functions
I think it's because you merged that other branch into dev perhaps, and then I pulled new changes into my dev and then rebased this branch to align with dev perhaps...I'm not sure why it did that honestly

2022-06-10 22:43 UTC, kushalkolar approved these changes

2022-06-10 22:43 UTC, merged