creating cache for faster access to results of previous cnmf extension calls
nel-lab/mesmerize-core pull request #62
Opened 2022-06-28 16:19 UTC by clewis7

adding file to extensions for a cache

cache should allow users to quickly access results of previously made calls to cnmf extensions that have the same ```function_name, args,``` and ```kwargs```

2022-06-28 19:39 UTC, clewis7 commented
will work on testing out cache for different cnmf and mcorr extension functions as well as checking reduced time in accessing!!

2022-06-29 04:30 UTC, kushalkolar requested changes
almost there! :D

2022-06-29 04:30 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +                    i, 2] == kwargs:
So numpy arrays simply don't return true if the arrays are equal. numpy arrays are used for passing component indices so we need to deal with them. And since the `kwargs` are a `dict` this will raise the following exception:

```python
In [1]: import numpy as np

In [2]: ixs = np.array([3, 1, 4, 5, 9])

... # a few lines are skipped but i basically made the following dict
In [6]: d
Out[6]: {'x': array([3, 1, 4, 5, 9]), 'y': [1, 2, 6, 9, 4], 'z': True}

In [8]: from copy import deepcopy
In [9]: d_copy = deepcopy(d)

# just to show that these have same vals but are in diff chunks of RAM
In [11]: hex(id(d_copy)) == hex(id(d))
Out[11]: False

In [12]: d == d_copy
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [12], in <cell line: 1>()
----> 1 d == d_copy

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

The reason for this exception is because the `==` operator works like this for numpy arrays, it's element-wise equality:

```python
In [15]: d['x'] == d_copy['x']
Out[15]: array([ True,  True,  True,  True,  True])

In [16]: d['y'] == d_copy['y']
Out[16]: True
```

So we need to use `np.array_equal`

```python
In [27]: np.array_equal(d['x'], d_copy['x'])
Out[27]: True

In [29]: d['x']
Out[29]: array([3, 1, 4, 5, 9])

In [30]: some_other_array = np.array([9, 5, 7])

In [31]: np.array_equal(d['x'], some_other_array)
Out[31]: False
```

You could implement something like this to check equality of each kwarg:
```python
In [32]: def _is_kwarg_val_equal(kwarg_val, cache_kwarg_val):
    ...:     if not type(kwarg_val) == type(cache_kwarg_val):
    ...:         return False
    ...: 
    ...:     if isinstance(cache_kwarg_val, np.ndarray):
    ...:         return np.array_equal(kwarg_val, cache_kwarg_val)
    ...:     else:
    ...:         return kwarg_val == cache_kwarg_val
```

2022-06-29 04:59 UTC, kushalkolar commented
also for some reason tests are failing for cnmfe, weird because they're passing on `master` and this branch has no diff with the tests on `master`. can check in details later.

2022-07-01 02:35 UTC, kushalkolar requested changes

2022-07-01 02:35 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +def check_arg_equality(args, cache_args):
You'll need to iterate through each arg or kwarg. You can split this into functions, one that is basically the same as this and another that calls this function for each item of the `args` and `kwargs`.

```python
def _check_arg_equality(val, cache_val):
  # leave as is

def _check_args_equality(args, cache_args):
  equality = list() # a list used to store the equality True/False for all args/kwargs
  if isinstance(args, tuple) # for args
    for arg, cache_arg in zip(args, cache_args): # zip will go through two iterables at once
      equality.append(_check_arg_equality(arg, cache_arg)
  else: # assume is dict for kwargs
    for k in args.keys():
      equality.append(_check_arg_equality(args[k], cache_args[k])
  # returns True is all vals are truth, I think this is the right way to do it, it might instead be (equality).all()
  return all(equality)
```

2022-07-01 15:04 UTC, clewis7 commented on mesmerize_core/caiman_extensions/cache.py
> +def check_arg_equality(args, cache_args):
okay, this is what I thought about last night...but then based on what you said previously I wasn't sure

should be fixed now

2022-07-01 16:48 UTC, kushalkolar requested changes

2022-07-01 16:48 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +            if len(self.cache.index) == self.cache_size:
Last thing that would be useful is to have the option for the cache size to be based on how large the cache is in RAM rather than number of items. Since things like cnmf output, reconstructed movie frames etc. are larger in size than things like paths. I suggest:

1. Having the option for the cache size to be in gigabytes for example.
  - This should be easy to implement, lookup how to find the size of objects in python. Note that it's different for numpy arrays and python built-in types. But also, look through some of the cnmf extension return vals and you'll see that some return types are dicts of numpy arrays, I think you can figure out how to handle those.
3. Use a separate cache instance for reconstructed movie and residuals.

2022-07-03 06:36 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +            if len(self.cache.index) == self.cache_size:
Also if cache size is 0, just return func(*args, **kwargs)

2022-07-03 12:53 UTC, clewis7 commented on mesmerize_core/caiman_extensions/cache.py
> +            if len(self.cache.index) == self.cache_size:
why can't I just use ```sys.getsizeof(cache_output)``` for each output being stored in the cache, would that not work for all output types?

2022-07-03 13:08 UTC, clewis7 commented
just did basic impl of using memory size, appears to be working when I test it out

wasn't completely sure how you wanted the bounds to work because the likelihood of the number you set for bytes being equivalent to the number that the output sizes in the cache will add up to be is unrealistic

can go back and alter impl so that if adding an item will cause cache to go over cache size, will remove the most recently used item...but this could also cause many items to be removed if removing simply a path for example will not necessarily cause a huge change to size of outputs but that was the most recently accessed item in the cache

2022-07-04 06:19 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +                return return_val
sorry this isn't what I meant

2022-07-04 06:42 UTC, kushalkolar requested changes

2022-07-04 06:42 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +
if `self.cache_size == 0` just return `func(instance, *args, **kwargs)`, this is effectively a way to disable the cache (useful for debugging etc.)

2022-07-04 06:42 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +        self.cache_size = cache_size
I'd just rename this to `size`. In pycharm you can have your cursor over the instance variable and then **Shift + F6** to change the name.

2022-07-04 06:42 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +    def _get_cache_size(self):
`_get_cache_size_bytes`

2022-07-04 06:42 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +            cache_size += sys.getsizeof(self.cache.iloc[i, 4])
this works only for python builtin types AFAIK, not for numpy arrays. Try it out in `ipython` and see what it looks like. Try numpy arrays of different shapes and different `dtype`, they should have different sizes.

2022-07-04 06:42 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +        if length_storage == True:
you can instead just have the `self.size` determine the storage type. For example, if the `size` kwarg is is a `str` and ends with `G` (for gigabyte) use `RAM`, if it is an `int` use as `ITEMS`.

2022-07-04 06:42 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +        return cache_size
return in gigabytes

2022-07-04 06:42 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +        return cache_size
`1024**3` bytes in RAM is 1GiB

2022-07-04 06:42 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +        return cache_size
that is `1024^3`

2022-07-04 06:42 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cnmf.py
> +cache = Cache()
After implementing the cache size stuff, set the default size of this to something like `1G`? @ArjunPutcha any thoughts on cache sizes?

For the reconstructed & residuals functions we can have a separate cache instance, maybe with a default size of `2G`.

In any case, the user can change the default sizes like this:

```python
from mesmerize.caiman_extensions.cnmf import cache
cache.size = 4G
```

2022-07-04 06:42 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +        return cache_size
Could also be useful to support megabytes, that is `1024**2`

2022-07-04 06:48 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +            elif self.storage_type == 'RAM':
There is a more elegant way to implement this code block

2022-07-04 06:48 UTC, kushalkolar commented
> just did basic impl of using memory size, appears to be working when I test it out
> 
> wasn't completely sure how you wanted the bounds to work because the likelihood of the number you set for bytes being equivalent to the number that the output sizes in the cache will add up to be is unrealistic
> 
> can go back and alter impl so that if adding an item will cause cache to go over cache size, will remove the most recently used item...but this could also cause many items to be removed if removing simply a path for example will not necessarily cause a huge change to size of outputs but that was the most recently accessed item in the cache

Yes you are right!

I'm assuming you mean removing the least recently used, not most recently used.

Anyways there's a very simple way on this [line 118](https://github.com/nel-lab/mesmerize-core/pull/62/files#diff-e3b9bc07230b418058e5f378944ed9863cb6f98454acd389758a2e21eb2ff51dR118) to make sure that it never exceeds the cache size! In general there's a more elegant way to implement your control flow here.

2022-07-04 06:54 UTC, kushalkolar commented
I think that the reason the tests are failing is because cached values are being returned even though new args have been passed. I'm guessing this because there's a mismatch in the shape of input arrays which corroborates with the size of `ixs_components`:
https://github.com/nel-lab/mesmerize-core/runs/7168946258?check_suite_focus=true#step:7:748
https://github.com/nel-lab/mesmerize-core/runs/7168946258?check_suite_focus=true#step:7:1058.

2022-07-05 15:57 UTC, clewis7 commented
last commit message should be ```"...should now work..."```

2022-07-05 16:52 UTC, kushalkolar requested changes

2022-07-05 16:52 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +            self.size = 1
Default size as `"1G"`

2022-07-05 16:52 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +                cache_size += sys.getsizeof(self.cache.iloc[i, 4].estimates)
you need to get the size of all the arrays inside estimates

2022-07-05 16:52 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +            elif isinstance(self.cache.iloc[i, 4], Tuple):
tuples can have any number of elements not just 2

2022-07-05 16:52 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +        if return_gig:
Just do this based on `self.size`, like `if self.size.endswith("G")`

2022-07-05 16:52 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +                return_val = func(instance, *args, **kwargs)
get the `return_val` and append it to the cache _after_ trimming the cache in case `return_val` is larger than `self.size`

2022-07-05 16:52 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +            if self.storage_type == 'ITEMS' and len(self.cache.index) == self.size:
I'd use `len(self.cache.index) >= self.size` just in case something ever goes wonky

2022-07-05 18:10 UTC, kushalkolar requested changes

2022-07-05 18:10 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +                cache_size += (self.cache.iloc[i, 4].estimates.A.data.nbytes + self.cache.iloc[i, 4].estimates.C.data.nbytes + self.cache.iloc[i, 4].estimates.b.data.nbytes + self.cache.iloc[i, 4].es
are these sufficient to sum upto ~90% the size of the object?

2022-07-05 18:10 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
>          else:
elif `self.size.endswith("M")`

2022-07-05 18:10 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +                    return_val = func(instance, *args, **kwargs)
this stuff should be outside the `while`!

2022-07-07 01:47 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +from builtins import list
??? builtins don't need to be imported by definition

2022-07-07 01:56 UTC, kushalkolar requested changes

2022-07-07 01:56 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +
sorry we can actually `return return_val` right here, otherwise it will always enter the next block of code which is unnecessary

2022-07-07 01:56 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +
@clewis7

2022-07-07 01:57 UTC, kushalkolar commented
Things left to do:

1. Tests
  - test that the MB and GB cache size limits work
  - test that cached vals are returned only when not present in cache dataframe (this appears to be an issue somewhere which is possibly why tests are failing).
2. Check if estimates.A, C, b and f sum up to ~90% the total size of the estimates object. You can just use ipython and a process memory profiler (even htop, or ksysguard) to verify this. Ask me if you want me to clarify.
3. Do we need to debug what's going on with the iterables containing numpy arrays?

2022-07-07 13:13 UTC, clewis7 commented
I only have two things left to debug with the cache and hopefully after fixing these issues the tests should pass:

(1) I need to fix the ```check_argument``` functions because when ```ixs_components``` are passed and the function has already been called, or vice versa, the cache is not differentiating that these are two different calls to the same function with different arguments and thus causes the tests to fail
(2) I still am not sure why the size of ```get_temporal_components()``` cannot be calculated by what I have because I have verified that the output is of type ```numpy.ndarray```, however the error that is being casted is an attribute error claiming that type list has no attribute data...makes absolutely no sense to me because the if block that should calculate the size of a ```numpy.ndarray``` is completely being skipped and then the output is being recognized as a tuple which is certainly not the case

Other than that, I will need to write the tests that you have mentioned above and then will need to fix the ```get_reconstructed_movie()``` and ```get_residuals()``` functions on the other PR so that I can add a separate cache for those

2022-07-08 17:53 UTC, kushalkolar commented
I just realized, for things like `get_spatial()`, `get_temporal()` etc. we should always return a _copy_ because otherwise the cached value would get changed if the user for example does stuff with the `temporal` downstream. We can have a default kwarg for all these cached functions `return_copy=True`. We should have the same thing for `get_reconstructed()` `get_residuals()` etc. but maybe default set as `return_copy=False` because these are larger arrays.

2022-07-08 20:06 UTC, kushalkolar requested changes

2022-07-08 20:06 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +    if len(args) != len(cache_args):
was this the issue for why the tests with specified idx_components failed?

2022-07-08 20:06 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
>              elif isinstance(self.cache.iloc[i, 4], tuple):
user might use list instead of tuple too, you can do:

```python
isinstance(cache_val, (tuple, list))
```

2022-07-08 20:06 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +                cache_size += (self.cache.iloc[i, 4].estimates.A.data.nbytes + self.cache.iloc[i, 4].estimates.C.data.nbytes + self.cache.iloc[i, 4].estimates.b.data.nbytes + self.cache.iloc[i, 4].es
@clewis7

2022-07-08 20:11 UTC, clewis7 commented on mesmerize_core/caiman_extensions/cache.py
> +    if len(args) != len(cache_args):
yes!! had to do with tuple equality assertion of an empty tuple and a non-empty tuple, this was the simple solution

2022-07-08 20:15 UTC, clewis7 commented
> I just realized, for things like `get_spatial()`, `get_temporal()` etc. we should always return a _copy_ because otherwise the cached value would get changed if the user for example does stuff with the `temporal` downstream. We can have a default kwarg for all these cached functions `return_copy=True`. We should have the same thing for `get_reconstructed()` `get_residuals()` etc. but maybe default set as `return_copy=False` because these are larger arrays.

Will implement after I fix residuals and reconstructed movie extensions

2022-07-08 21:57 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +                cache_size += (self.cache.iloc[i, 4].estimates.A.data.nbytes + self.cache.iloc[i, 4].estimates.C.data.nbytes + self.cache.iloc[i, 4].estimates.b.data.nbytes + self.cache.iloc[i, 4].es
```python
sizes = list()
for attr in cnmf_obj.estimates.__dict__.values():
    if isinstance(attr, np.ndarray):
        sizes.append(attr.data.nbytes)
    else:
        sizes.append(getsizeof(attr))
```

2022-07-08 23:57 UTC, kushalkolar requested changes

2022-07-08 23:57 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +def _return_wrapper(output):
add an arg, `copy`

2022-07-08 23:57 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +                return _return_wrapper(return_val)
add arg, `copy=return_copy`

And, at the very beginning of the ``_use_cache`` function get the kwarg for `copy`

```python
_use_cache(instance, *args, **kwargs):
  if "copy" in kwargs.keys():
    return_copy = kwargs["copy"]
  else:
    return_copy = True
``

2022-07-08 23:57 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +                    return _return_wrapper(self.cache.iloc[i, 4])
add arg, `copy=return_copy`

2022-07-08 23:57 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +                return _return_wrapper(self.cache.iloc[len(self.cache.index) - 1, 4])
add arg, `copy=return_copy`

2022-07-08 23:57 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +            return _return_wrapper(return_val)
add arg, `copy=return_copy`

2022-07-08 23:58 UTC, kushalkolar commented
yay other than my comments about the copy, just need to write tests for cache!

- test that the MB and GB cache size limits work, set something small for the tests like 100MB
- test that cached vals are returned only when not present in cache dataframe
- tests should be in a separate test function entirely, run a fresh batch of mcorr and cnmf in this function and tests that the cache stuff works here.

2022-07-12 05:13 UTC, kushalkolar commented
So this makes a big difference, reconstructed, residuals etc. movies are now FAST random-access scrollable. The majority of the time is spent in fetching data, the outer product doesn't take very long so we don't need to decorate `get_reconstructed()`, `get_residuals()` etc.. I tried and it actually slows it down considerably! 

https://user-images.githubusercontent.com/9403332/178413347-8eded76a-2334-42dc-a662-4341db8c97e6.mp4

https://user-images.githubusercontent.com/9403332/178413614-54e34bca-30fd-4b56-b32d-341de4c1a1df.mp4

2022-07-13 20:38 UTC, kushalkolar requested changes
I think it'd also be useful to have cache tests to make sure that it's returning the cached vals for the correct function and item (by checking the UUID).

2022-07-13 20:38 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/cache.py
> +            if self.size == 0:
So this effectively disables the cache?

2022-07-13 20:38 UTC, kushalkolar commented on tests/test_core.py
> +    import time
put import at top of file

2022-07-13 20:38 UTC, kushalkolar commented on tests/test_core.py
> +
can you just puts comments for what all the following tests do, we won't understand it in a few months

2022-07-18 02:27 UTC, kushalkolar approved these changes
LGTM! Awesome job!

2022-07-21 07:20 UTC, kushalkolar requested changes
Just a few minor things and I will merge! :D Test should pass on github after these changes!

2022-07-21 07:20 UTC, kushalkolar commented on mesmerize_core/caiman_extensions/mcorr.py
> +    @cache.use_cache
this shouldn't be cached since a memmaped array is basically like a pointer to stuff on disk

2022-07-21 07:20 UTC, kushalkolar commented on tests/test_core.py
> +    set_parent_raw_data_path(vid_dir)
just add this as the first line of `test_cache()` and tests should finally pass!

```python
cnmf.cache.clear_cache()
```

the extension calls in `test_cnmf()` etc. were populating the cache dataframe which is why the `test_cache()` stuff was failing when the entire `test_core.py` is run, causing the first `assert` which relies on cache size to be 1 to fail.

2022-07-21 07:20 UTC, kushalkolar commented on tests/test_core.py
> +    set_parent_raw_data_path(vid_dir)
also add a print statement `print("*** Testing cache ***")`

2022-07-21 07:20 UTC, kushalkolar commented on tests/test_core.py
> +    print("Testing cnmf")
remove this print statement, can be confusing when looking at CI test logs

2022-07-21 23:45 UTC, kushalkolar approved these changes
yay, test pass, going to merge

2022-07-21 23:45 UTC, merged