updating tests to cnmf, still need to upload to zenodo and fix download
nel-lab/mesmerize-core pull request #73
Opened 2022-07-13 15:20 UTC by clewis7

tests will not pass as of right now, but wanted to upload changes for tests passing on my end

about to update tests for cnmfe then I will fix zenodo upload

2022-07-13 23:30 UTC, kushalkolar commented
> tests will not pass as of right now, but wanted to upload changes for tests passing on my end

seems like the tests pass though?

2022-07-13 23:44 UTC, kushalkolar requested changes

2022-07-13 23:44 UTC, kushalkolar commented on tests/test_core.py
> +        ground_truths_dir.joinpath("cnmf", "reconstructed_movie_new.npy")
instead of calling it "reconstructed_movie_new" I'd call it "reconstructed_AouterC", for the others "reconstructed_A-outer-C-plus-b-outer-f" or something so that we understand what we did next year

2022-07-13 23:44 UTC, kushalkolar commented on tests/test_core.py
> +    cnmf_residuals = df.iloc[-1].cnmf.get_residuals()
probably also good to make sure that `assert_allclose(cnmf_residuals, cnmf.get_input_memmap() - reconstructed)`

2022-07-13 23:44 UTC, kushalkolar commented on tests/test_core.py
> +    ixs_reconstructed_movie_new = df.iloc[-1].cnmf.get_reconstructed_movie(ixs_components)
the first argument for `cnmf.get_reconstructed_movie()` is `ixs_frames` not components

2022-07-13 23:44 UTC, kushalkolar commented on tests/test_core.py
> +    ixs_reconstructed_background = df.iloc[-1].cnmf.get_reconstructed_background(ixs_components)
similar to above, the first argument for `cnmf.get_reconstructed_background()` is ixs_frames not components

2022-07-13 23:44 UTC, kushalkolar commented on tests/test_core.py
> +    cnmfe_ixs_reconstructed_movie_AC = df.iloc[-1].cnmf.get_reconstructed_movie(ixs_components)
same comments as above for cnmf

2022-07-13 23:44 UTC, kushalkolar commented on tests/test_core.py
> +    cnmfe_ixs_reconstructed_background = df.iloc[-1].cnmf.get_reconstructed_background(ixs_components)
same comments as above for cnmf

2022-07-13 23:44 UTC, kushalkolar commented on tests/test_core.py
> +    cnmfe_ixs_reconstructed_movie = df.iloc[-1].cnmf.get_reconstructed_movie(ixs_components) + df.iloc[
same comments as above for cnmf

2022-07-13 23:44 UTC, kushalkolar commented on tests/test_core.py
> +    cnmfe_ixs_residuals = df.iloc[-1].cnmf.get_residuals(ixs_components)
same comments as above for cnmf

2022-07-14 04:01 UTC, clewis7 commented
> > tests will not pass as of right now, but wanted to upload changes for tests passing on my end
> 
> seems like the tests pass though?

yes, this push was before zenodo upload, tests should pass now I just need to implement the changes you had

2022-07-14 04:30 UTC, kushalkolar commented
GO SLEEP AND REST

On Thu, Jul 14, 2022, 00:01 Caitlin Lewis ***@***.***> wrote:

> tests will not pass as of right now, but wanted to upload changes for
> tests passing on my end
>
> seems like the tests pass though?
>
> yes, this push was before zenodo upload, tests should pass now I just need
> to implement the changes you had
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nel-lab/mesmerize-core/pull/73#issuecomment-1183959825>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACHXXRDWLNDRGXDTQU3QA2TVT6GKVANCNFSM53PDUU5A>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-07-21 07:22 UTC, kushalkolar commented
this ready to merge?

2022-07-21 21:16 UTC, clewis7 commented
> this ready to merge?

should be, I don't have anything else I need to add

2022-07-21 23:46 UTC, kushalkolar approved these changes
lgtm

2022-07-21 23:46 UTC, merged